import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { treaty } from "../../treaty";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextAuth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  console.log({ session });

  const { data: dogs } = await treaty.api.elysia.dogs.get();
  return (
    <html lang="en">
      <body className={inter.className}>
        {dogs?.map((dog) => (
          <li key={dog}>{dog}</li>
        ))}
      </body>
    </html>
  );
}
